title: aizentranza.github.io
author: Kinoshita Naoki
email: 'kinoshita_naoki@mail.goo.ne.jp'
url: https://aizentranza.github.io
twitter_username: kinoshita_naoki
github_username: aizentranza
description: GitHub Pages Root Contents
theme: minima
